DROP TABLE IF EXISTS cars CASCADE;
CREATE TABLE cars (
  id SERIAL PRIMARY KEY NOT NULL,
  seller_id INTEGER REFERENCES users(id) ON DELETE CASCADE,
  make VARCHAR(255) NOT NULL,
  model VARCHAR(255) NOT NULL,
  model_colour VARCHAR(255) NOT NULL,
  year INTEGER NOT NULL,
  doors INTEGER NOT NULL,
  descriptions TEXT,
  thumbnail_url VARCHAR(255) NOT NULL,
  cover_url VARCHAR(255) NOT NULL,
  car_price INTEGER NOT NULL DEFAULT 0,
  sold BOOLEAN NOT NULL DEFAULT FALSE
);
